name: python-fastapi
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - ../.env.development
    volumes:
      - ../:/app
